title: kaiwhata.com
#email: your-email@example.com
description: "Elf: Cybersecurity + Sheep"  # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
domain: kaiwhata.com
url: "https://kaiwhata.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kaiwhata
github_username:  kaiwhata
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
plugins: 
  - jemoji
